(**** beginning of start.gcode ****)
(This file is for a MakerBot Thing-O-Matic)
(**** begin initialization commands ****)
G21 (set units to mm)
G90 (set positioning to absolute)
M108 R1.98 (set extruder speed)
M103 (Make sure extruder is off)
M104 S225 T0 (set extruder temperature default 225)
M109 S110 T0 (set heated-build-platform temperature default 125)
(**** end initialization commands ****)
(**** begin homing ****)
G162 Z F500 (home Z axis maximum)
G92 Z10 (set Z to 0)
G1 Z0 (move z down 10)
G162 Z F100 (home Z axis maximum)
G161 X Y F2500 (home XY axes minimum)
M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
(**** end homing ****)
M6 T0 (wait for toolhead parts, nozzle, HBP, etc., to reach temperature)
G0 X-52 Y-58  (to front left corner)
G1 Z0.50      (just over surface)
M108 R2.0           (set stepper extruder speed)
M101                (start extruder)
G4 P2000            (build up a turd)
(**** end of start.gcode ****)
