(**** beginning of start.gcode ****)
(This file is for a MakerBot Cupcake w/ Stepstruder and HBP)
(**** begin initialization commands ****)
M104 S225 T0 (set extruder temperature default 225)
M109 S110 T0 (set heated-build-platform temperature default 125)
G21 (set units to mm)
G90 (set positioning to absolute)
G92 X0 Y0 Z0 (You are now at 0,0,0)
M106 (Extruder Fan On)
(**** end initialization commands ****)
G0 Z15 (Move up for test extrusion)
M108 R2 (set extruder speed)
M6 T0 (Wait for tool to heat up)
G04 P5000 (Wait 5 seconds)
M101 (Extruder on, forward)
G04 P5000 (Wait 5 seconds)
M103 (Extruder off)
M01 (The heater is warming up and will do a test extrusion.  Click yes after you have cleared the nozzle of the extrusion.)
G0 Z0(Go back to zero.)
(**** end of start.txt ****)
