(**** beginning of start.gcode ****)
(This file is for a whiteAnt)
(**** begin initialization commands ****)
M104 S205 T0 (set extruder temperature default 225)
G21 (set units to mm)
G90 (set positioning to absolute)
G92 X0 Y0 Z0 (You are now at 0,0,0)
M108 R1.98 (set extruder speed)
M103 (Make sure extruder is off)
(**** end initilization commands ****)
G1 X0 Y0 Z15 F200 (Move up for test extrusion)
M6 T0 (Wait for tool to heat up)
G04 P5000 (Wait 5 seconds)
M101 (Extruder on, forward)
G04 P5000 (Wait 5 seconds)
M103 (Extruder off)
M01 (The heater is warming up and will do a test extrusion.  Click yes after you have cleared the nozzle of the extrusion.)
G1 X0 Y0 Z0 (Go back to zero.)
(**** end of start.txt ****)
