(**** beginning of start.gcode ****)
(This file is for a whiteAnt)
(**** begin initialization commands ****)
G21 (set units to mm)
G90 (set positioning to absolute)
M108 R1.98 (set extruder speed)
M103 (Make sure extruder is off)
M104 S205 T0 (set extruder temperature default 225)
(**** end initilization commands ****)
(**** begin homing ****)
G162 Z F800 (home Z axis maximum)
G161 X Y F3000 (home XY axes minimum)
M6 T0 (wait for toolhead parts, nozzle, HBP, etc., to reach temperature)
G92 Z100 ( ---=== Set Z axis maximum ===--- )
G92 X-80 Y-95 (set zero for X and Y)
G1 X-80 Y-95 Z0 F800 (move Z to 0)
G1 X0 Y0 Z0 F3000 (move Z and Y to 0)
(**** end homing ****)
(**** end of start.txt ****)
